// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package tutorial

import (
	"database/sql"
)

type Comment struct {
	ID        int64
	Text      string
	PostID    int64
	CreatedAt sql.NullTime
}

type Post struct {
	ID        int64
	Title     string
	Text      string
	CreatedAt sql.NullTime
}
