// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Comment struct {
	ID        string       `json:"id"`
	Text      string       `json:"text"`
	PostID    string       `json:"post_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Post struct {
	ID        string       `json:"id"`
	Title     string       `json:"title"`
	Text      string       `json:"text"`
	CreatedAt sql.NullTime `json:"created_at"`
}
